url: "https://sinakitagami.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: SinaKitagami
description: >- # this means to ignore newlines until "baseurl:"
  北上思惟奈(Sina-Kitagami)は、mii-10によって作成された、高機能/高性能のDiscordボットです。現在、50サーバー以上で使われています。あなたも使ってみませんか?
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title

plugins:
  - jekyll-feed
markdown: kramdown
lang: ja-jp